from pathlib import Path
jp=Path("C:/Users/raju2/OneDrive/Documents/py/log.txt")
u=jp.write_text("NOOOO")
with open("C:/Users/raju2/OneDrive/Documents/py/log.txt", "r") as v:
 x=v.read()
f =open("C:/Users/raju2/OneDrive/Documents/py/log.txt", "r")
d=open("C:/Users/raju2/OneDrive/Documents/py/log1.txt", "w")
c=open("C:/Users/raju2/OneDrive/Documents/py/log1.txt", "a")
line_test=f.readlines()
line1=f.readline()
line2=f.readline()
s=d.write("HELLO IAM GOOD")
z=c.write("ANOTHER GOOD BOY")
data=f.read()
print(line_test)
print(data)
print(" ",line1,line2)
print(d,c)
print(x)
f.close()
d.close()